#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"

require_relative "lib/installer_release"

options = {}
OptionParser.new do |parser|
  parser.on("--archive PATH") { |value| options[:archive] = value }
  parser.on("--output PATH") { |value| options[:output] = value }
  parser.on("--version VERSION") { |value| options[:version] = value }
  parser.on("--channel CHANNEL") { |value| options[:channel] = value }
  parser.on("--platform PLATFORM") { |value| options[:platform] = value }
  parser.on("--architecture ARCHITECTURE") { |value| options[:architecture] = value }
end.parse!

required = %i[archive output version channel platform architecture]
missing = required.reject { |key| options[key] }
abort "missing required options: #{missing.join(", ")}" unless missing.empty?

release = { "tag" => "v#{options[:version]}", "version" => options[:version], "channel" => options[:channel],
            "platform" => options[:platform], "architecture" => options[:architecture] }
InstallerRelease::Manifest.write(options[:output], archive: options[:archive], release: release)
